version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    volumes:
      - ./user-service:/app

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    volumes:
      - ./product-service:/app

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    volumes:
      - ./order-service:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./frontend:/app