apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: shreyash1414/cloud_shop_project-order-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
