apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    release: prometheus 
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
  type: NodePort
