apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: shreyash1414/cloud_shop_project-product-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
